import Navbar from "./components/Navbar";
import CollapsibleSection from "./components/CollapsibleSection";

// Example data (you'll replace this with actual content parsed from the DOCX file)
const sections = [
  {
    id: "Faalangst",
    title: "Faalangst",
    subsections: [
      { title: "Inleiding", content: "Faalangst is een probleem dat vaak voorkomt bij jongeren en zeker in schoolcontexten sterk naar voren komt. Het verwijst naar de intense angst om te falen in situaties waarin een prestatie geleverd moet worden. Dit kan gaan om examens, spreekbeurten, sportwedstrijden of zelfs sociale interacties waarbij men bang is om negatief beoordeeld te worden. Hoewel een beetje spanning normaal is, kan faalangst het functioneren van een jongere ernstig belemmeren als het te vaak of te hevig voorkomt." },
      { title: "Wat is het?", content: "Faalangst is een vorm van angst die optreedt wanneer iemand zich bedreigd voelt in een situatie waarin prestaties verwacht worden. De persoon denkt op voorhand al dat hij of zij zal falen en kan hierdoor blokkeren of zich volledig terugtrekken. Het is belangrijk om te beseffen dat faalangst niet altijd zichtbaar is: sommige leerlingen verbergen het achter perfectionisme, anderen worden stil en onzichtbaar in de klas. Cognitieve faalangst komt het meest voor in schoolcontext: hierbij vreest een leerling dat hij zal falen op een toets of opdracht, ondanks een degelijke voorbereiding." },
      { title: "Hoe herken je het?", content: "Faalangst kent een breed scala aan symptomen. Lichamelijk kunnen jongeren last hebben van zweten, trillen, hartkloppingen, buikpijn of kortademigheid. Mentaal treden vaak negatieve automatische gedachten op zoals 'ik kan dit niet', 'ik zal dom overkomen' of 'ik ga weer falen'. Deze gedachten zorgen voor spanning, concentratieverlies en prestatievermindering. Daarnaast kan er sprake zijn van vermijdingsgedrag: het uitstellen van studeren, geen spreekbeurten durven geven of zelfs school vermijden. Sommige jongeren krijgen black-outs of paniekaanvallen vlak voor een opdracht of toets. Ze weten op dat moment niets meer, ook al hadden ze de leerstof goed ingestudeerd." },
      { title: "Welke aanpak is mogelijk?", content: "Een goede aanpak van faalangst vereist enerzijds inzicht in de onderliggende gedachten, en anderzijds het aanleren van vaardigheden om met spanning om te gaan. Cognitieve gedragstherapie is hierbij een bewezen methode: jongeren leren om negatieve automatische gedachten uit te dagen en realistisch te denken over hun prestaties. Ook het oefenen van faalmomenten in veilige omstandigheden, zoals rollenspelen of presentaties in kleine groep, helpt om de angst te normaliseren. Verder kunnen ontspanningstechnieken zoals diepe ademhaling, visualisatie en mindfulness bijdragen aan het verlagen van fysieke spanning. Het is belangrijk dat jongeren leren hun inspanning te waarderen, en niet enkel het resultaat. Ouders en leerkrachten kunnen ondersteunen door constructieve feedback te geven en ruimte te bieden voor groei." },
      { title: "Wanneer hulp inschakelen?", content: "Als de faalangst zo ernstig is dat het het dagelijks leven belemmert – bijvoorbeeld als een leerling school vermijdt, constant huilt of slaapproblemen heeft – is professionele hulp aangewezen. Een gesprek met een CLB-medewerker, leerlingbegeleider of psycholoog kan inzicht geven in de oorzaak van de angst. Vaak wordt er gewerkt met cognitieve gedragstherapie waarbij jongeren leren om hun negatieve gedachten uit te dagen en anders te denken over falen. Soms wordt er ook gewerkt in groepjes met andere jongeren die faalangst ervaren, zodat ze leren dat ze niet alleen zijn. Vroegtijdige hulp is belangrijk om te voorkomen dat faalangst leidt tot schooluitval, burn-out of depressie." },
      { title: "Wist je dat?", content: "Bij faalangst neemt het angstcentrum in je hersenen, de amygdala, de controle over. Hierdoor functioneert je denkvermogen tijdelijk minder goed, wat leidt tot black-outs of paniek. Je lichaam zit dan in een vecht-of-vluchtmodus, ook al is er geen echt gevaar. Door je hersenen te trainen met ademhaling of meditatie, kun je leren om rustiger te reageren op zulke situaties." },
    ],
  },
  {
    id: "Stress",
    title: "Stress",
    subsections: [
      { title: "Inleiding", content: "Stress is een veelvoorkomend fenomeen, ook bij jongeren. Het betreft een natuurlijke reactie van het lichaam en de geest op situaties die als uitdagend of bedreigend worden ervaren. Hoewel stress soms functioneel is en kan aanzetten tot actie, wordt het problematisch wanneer deze te frequent of te intens voorkomt." },
      { title: "Wat is het precies?", content: "Stress ontstaat wanneer het lichaam zich voorbereidt op actie bij een vermeende dreiging. Hierbij komen stresshormonen vrij zoals adrenaline en cortisol, die het lichaam in een staat van paraatheid brengen. Dit mechanisme was in vroegere tijden essentieel voor overleving. Vandaag zijn de bedreigingen vaak mentaal of sociaal van aard, zoals examens, sociale druk of conflicten. Wanneer deze toestand chronisch wordt, raken lichaam en geest uit balans." },
      { title: "Hoe is het te herkennen?", content: "Stress uit zich zowel lichamelijk als psychisch. Veelvoorkomende klachten zijn gespannen spieren, hoofdpijn, vermoeidheid, concentratieproblemen, slaapproblemen, piekergedachten en prikkelbaarheid. Gedragsveranderingen, zoals terugtrekking, uitstelgedrag of verhoogde emotionaliteit, zijn eveneens signalen van aanhoudende stress." },
      { title: "Welke aanpak is mogelijk?", content: "Stressmanagement begint met het herkennen van de eigen stresssignalen. Vervolgens kan er gewerkt worden aan stressvermindering via leefstijlaanpassingen: voldoende slaap, gezonde voeding, regelmatige beweging en voldoende ontspanning zijn fundamenteel. Time-management is een belangrijke vaardigheid: jongeren kunnen leren hun taken beter te plannen, prioriteiten te stellen en pauzes in te lassen. Ademhalingsoefeningen, yoga en mindfulness helpen om het zenuwstelsel tot rust te brengen. Verder kan het helpen om piekergedachten op te schrijven of te delen met iemand uit de omgeving. Bij langdurige of hevige stress kunnen psycho-educatie of therapeutische gesprekken met een begeleider of psycholoog structurele verlichting bieden." },
      { title: "Wanneer en waar hulp zoeken?", content: "Professionele hulp is aangewezen wanneer stress het dagelijks functioneren belemmert, zoals bij slaapproblemen, chronische vermoeidheid, emotionele uitputting of terugkerende fysieke klachten. Gesprekken met een schoolpsycholoog, het CLB of externe therapeuten kunnen handvatten bieden om beter met stress om te gaan." },
      { title: "Wist je dat...?", content: "Langdurige stress kan een structurele impact hebben op de hersenen. De activiteit van de prefrontale cortex, verantwoordelijk voor denkvermogen en planning, neemt af, terwijl het angstcentrum (de amygdala) actiever wordt. Hierdoor kunnen stressreacties sneller optreden, maar deze effecten zijn omkeerbaar met rust, therapie en herstellende gewoonten." },
    ],
  },
  {
    id: "Perfectionisme",
    title: "Perfectionisme",
    subsections: [
      { title: "Inleiding", content: "Perfectionisme komt veel voor bij jongeren die hoge eisen aan zichzelf stellen. Hoewel dit in eerste instantie leidt tot inzet en nauwkeurigheid, kan het op langere termijn leiden tot overbelasting, faalangst en uitstelgedrag. Het is belangrijk om perfectionisme te herkennen, bespreekbaar te maken en te leren hoe hiermee om te gaan." },
      { title: "Wat is het precies?", content: "Perfectionisme is een innerlijke drang om altijd foutloos te presteren en te voldoen aan zelfopgelegde of externe normen. Het gaat gepaard met de overtuiging dat fouten onaanvaardbaar zijn en dat succes het enige acceptabele resultaat is. Perfectionisme is geen officiële diagnose, maar wordt vaak gezien als een risicofactor voor psychische klachten zoals burn-out, depressie en angststoornissen. Perfectionisme kan cognitief, gedragsmatig en emotioneel tot uiting komen en wordt vaak gevoed door negatieve zelfspraak en een kritische innerlijke stem." },
      { title: "Hoe is het te herkennen?", content: "Perfectionisme uit zich in gedrag zoals overdreven herhalen of verbeteren van taken, moeite met delegeren, langdurig piekeren over details, of het vermijden van uitdagingen uit angst om te falen. Jongeren met perfectionistische trekken kunnen zichzelf als mislukkeling beschouwen, zelfs wanneer zij objectief gezien goed presteren. Daarnaast komt vaak uitstelgedrag voor: omdat het eindresultaat perfect moet zijn, wordt de taak pas gestart als alles ‘klaar’ is – wat zelden het geval is. Andere tekenen zijn stressklachten, slaapproblemen, verminderde motivatie en een laag zelfbeeld." },
      { title: "Welke aanpak is mogelijk?", content: "Een belangrijke stap is het herkennen van perfectionistische denkpatronen. Door middel van cognitieve gedragstherapie kunnen jongeren leren om hun overtuigingen te bevragen en meer realistische normen voor zichzelf te ontwikkelen. Zelfcompassie is hierbij een belangrijk element: leren mild te zijn voor zichzelf, fouten toe te laten als onderdeel van het leerproces, en zichzelf te waarderen los van prestaties. Daarnaast is het nuttig om doelen op te splitsen in haalbare stappen, en regelmatig stil te staan bij wat goed ging. Het bijhouden van een successen- of groeidagboek kan dit proces ondersteunen." },
      { title: "Wanneer en waar hulp zoeken?", content: "Professionele begeleiding is aangewezen wanneer perfectionisme leidt tot uitputting, depressieve gevoelens, angstklachten of ernstig verminderde schoolprestaties. Gesprekken met een psycholoog, leerlingbegeleider of CLB kunnen jongeren helpen om inzicht te krijgen in hun denkpatronen en om alternatieve strategieën te ontwikkelen. Ook groepstherapie, waarin jongeren ervaringen met perfectionisme delen, kan steun en normalisering bieden." },
      { title: "Wist u dat...?", content: "Perfectionisme komt vaker voor in omgevingen waar prestaties sterk gewaardeerd worden. Het wordt versterkt door sociale media, waarin vooral successen en uiterlijke perfectie worden gedeeld. Uit onderzoek blijkt dat jongeren die dagelijks veel tijd op sociale media doorbrengen, vaker negatieve zelfevaluaties en prestatiegerichte stress ervaren." },

    ],
  },
  {
    id: "Mindfulness",
    title: "Mindfulness",
    subsections: [
      { title: "Inleiding", content: "In een snel veranderende en veeleisende wereld worden jongeren geconfronteerd met constante prikkels, verwachtingen en prestatiedruk. Mindfulness biedt een tegengewicht door hen te leren met aandacht en rust aanwezig te zijn in het hier en nu. Het helpt om beter om te gaan met stress en emoties, en bevordert het welzijn op lange termijn." },
      { title: "Wat is het precies?", content: "Mindfulness is een aandachtstraining die mensen leert om zonder oordeel op te merken wat er in het moment gebeurt, zowel intern als extern. Het wordt vaak aangeleerd via meditatie, ademhalingstechnieken, lichaamsoefeningen en bewuste waarneming van gedachten en gevoelens. Door regelmatige beoefening ontwikkelen jongeren een grotere veerkracht, meer zelfinzicht en een verbeterd concentratievermogen. Mindfulness is geen religie of therapie, maar een universele methode die inzetbaar is in het dagelijks leven." },
      { title: "Hoe is het te herkennen?", content: "Jongeren die baat hebben bij mindfulness ervaren vaak stress, piekeren veel, hebben last van faalangst of moeite met concentratie. Typische klachten zijn lichamelijke spanningen, vermoeidheid, slapeloosheid of prikkelbaarheid. Ook bij jongeren die overmatig nadenken of worstelen met emotieregulatie, kan mindfulness verlichting bieden. Wanneer mindfulness wordt geïntegreerd in het dagelijkse leven, neemt de gevoeligheid voor negatieve prikkels af." },
      { title: "Welke aanpak is mogelijk?", content: "Mindfulness kan worden aangeleerd via groepslessen, apps, audiobegeleiding of individuele begeleiding. Oefeningen zoals de bodyscan, ademruimte of de 5-4-3-2-1-oefening helpen om uit het hoofd te komen en het lichaam als anker te gebruiken. Door dagelijks te oefenen, ontwikkelen jongeren meer innerlijke rust en kunnen zij beter omgaan met moeilijke gedachten of emoties. Scholen kunnen mindfulness inpassen via korte oefeningen tijdens de lesdag, wat bijdraagt aan klasrust en verhoogde leerprestaties." },
      { title: "Wanneer en waar hulp zoeken?", content: "Bij jongeren met aanhoudende stressklachten, angststoornissen of depressieve symptomen kan mindfulness deel uitmaken van een breder behandelingsplan. Therapeuten bieden mindfulness-based cognitive therapy (MBCT) aan, waarin mindfulness gecombineerd wordt met psychologische begeleiding. Het is belangrijk om begeleiding te zoeken bij een gecertificeerde trainer wanneer er sprake is van complexe psychische klachten." },
      { title: "Wist je dat...?", content: "Neurowetenschappelijk onderzoek toont aan dat mindfulness structurele veranderingen teweegbrengt in de hersenen. Gebieden die betrokken zijn bij aandacht, zelfregulatie en empathie worden actiever en beter ontwikkeld. Regelmatige beoefening versterkt het werkgeheugen en vermindert de activiteit van het default mode network, dat geassocieerd wordt met piekergedrag en afleiding." },
    ],
  },
  {
    id: "Yoga",
    title: "Yoga",
    subsections: [
      { title: "Inleiding", content: "Yoga is een eeuwenoude holistische methode die lichaam, geest en ademhaling op elkaar afstemt. In moderne context wordt yoga ingezet als stressverlagende techniek, ter bevordering van concentratie en ter ondersteuning van lichamelijk en psychisch welzijn bij jongeren." },
      { title: "Wat is het precies?", content: "Yoga omvat fysieke houdingen (asana’s), ademhalingstechnieken (pranayama) en mentale focus. Deze elementen werken samen om het zenuwstelsel te kalmeren, de flexibiliteit en kracht van het lichaam te bevorderen, en innerlijke rust te cultiveren. Afhankelijk van de gekozen stijl ligt het accent meer op ontspanning of fysieke inspanning. Yoga is laagdrempelig en kan aangepast worden aan het niveau en de behoefte van jongeren." },
      { title: "Hoe is het te herkennen?", content: "Jongeren met stressklachten, spanning in het lichaam, slaapmoeilijkheden of aandachtsproblemen kunnen baat hebben bij yoga. Ook wie moeite heeft met het herkennen van lichaamssignalen of emotieregulatie, kan via yoga meer lichaamsbewustzijn en zelfcontrole ontwikkelen. Regelmatige beoefening leidt tot verlaging van het stresshormoon cortisol, verbetering van het slaappatroon en versterking van de geestelijke weerbaarheid." },
      { title: "Welke aanpak is mogelijk?", content: "Yoga kan individueel, in groep of klassikaal worden beoefend. Belangrijke houdingen voor ontspanning zijn de kindhouding, de kat-koe-beweging en de houding met benen tegen de muur. Daarnaast worden ademhalingsoefeningen zoals buikademhaling of box breathing gebruikt om het zenuwstelsel te kalmeren. Voor optimale effecten wordt aanbevolen om yoga minstens twee à drie keer per week te beoefenen, maar zelfs korte sessies van 10 minuten per dag kunnen al merkbare voordelen bieden." },
      { title: "Wist je dat...?", content: "Studies tonen aan dat yoga bij adolescenten leidt tot een verbeterd zelfbeeld, verhoogde motivatie op school en een afname van depressieve symptomen. De ademhalingscomponent van yoga heeft bovendien een directe invloed op het autonome zenuwstelsel, wat het herstelvermogen van het lichaam stimuleert." },
    ],
  },
  {
    id: "Angst",
    title: "Angst",
    subsections: [
      { title: "Inleiding", content: "Angst is een fundamentele emotionele reactie die van oudsher diende om gevaar tijdig te herkennen. In de moderne samenleving kan angst echter optreden in situaties die objectief gezien geen direct gevaar vormen. Bij jongeren uit dit zich vaak in schoolse of sociale contexten." },
      { title: "Wat is het precies?", content: "Angst activeert het autonome zenuwstelsel, wat leidt tot een verhoogde hartslag, versnelde ademhaling en gespannen spieren. Deze reactie vindt zijn oorsprong in de amygdala, een hersenstructuur die dreiging detecteert. In situaties zoals toetsen, sociale interacties of onverwachte veranderingen kan deze reactie overdreven of ongepast zijn. Bij frequente of intense angst spreekt men van een angststoornis." },
      { title: "Hoe is het te herkennen?", content: "Angst uit zich fysiek in klachten zoals beven, transpiratie, buikpijn, misselijkheid en kortademigheid. Psychisch komen negatieve gedachten voor, zoals faalangst of rampdenken. Gedragsmatig is er vaak sprake van vermijding van situaties die als bedreigend worden ervaren. Paniekaanvallen kunnen voorkomen, waarbij een gevoel van controleverlies en intense lichamelijke reacties optreden." },
      { title: "Welke aanpak is mogelijk?", content: "De aanpak van angstklachten bestaat vaak uit een combinatie van psycho-educatie, ademhalingstechnieken, en geleidelijke blootstelling aan beangstigende situaties. Jongeren leren hun angstige gedachten te herkennen en er afstand van te nemen. Cognitieve gedragstherapie helpt bij het doorbreken van negatieve denkpatronen. Via stappenplannen kunnen vermeden situaties langzaam opnieuw worden opgebouwd, zoals het geleidelijk spreken in de klas of deelnemen aan sociale activiteiten. Daarnaast is ontspanning via beweging, creatieve expressie of mindfulness effectief bij het kalmeren van het zenuwstelsel. Ouders, leerkrachten en hulpverleners spelen een belangrijke rol door steun te bieden zonder te forceren." },
      { title: "Wanneer en waar hulp zoeken?", content: "Wanneer angst leidt tot schoolverzuim, sociale isolatie of ernstige emotionele klachten, is het raadzaam professionele hulp in te schakelen. Psychologische begeleiding, eventueel in combinatie met groepsbehandeling of medicatie, kan de klachten verlichten en het functioneren verbeteren. Het CLB of een erkend therapeut kunnen hierbij ondersteunen." },
      { title: "Wist je dat...?", content: "Onderzoek wijst uit dat jongeren met angststoornissen zich vaak bewust zijn van het irrationele karakter van hun gedachten. Desondanks ervaren zij hun gevoelens als overweldigend. Door het geleidelijk aangaan van vermeden situaties kan het brein leren dat het 'gevaar' beheersbaar is, wat leidt tot afname van de angstreactie." },
    ],
  },
  {
    id: "Prestatiedruk",
    title: "Prestatiedruk",
    subsections: [
      { title: "Inleiding", content: "Prestatiedruk is een veelvoorkomende vorm van stress bij jongeren, vooral in de context van school en studie. Het verwijst naar de spanning die iemand ervaart door de overtuiging te moeten voldoen aan hoge verwachtingen van zichzelf of van anderen. Hoewel een zekere mate van druk stimulerend kan werken, leidt overmatige prestatiedruk tot psychische en lichamelijke klachten, en kan het het functioneren ernstig belemmeren." },
      { title: "Wat is het precies?", content: "Prestatiedruk ontstaat wanneer iemand voortdurend het gevoel heeft te moeten presteren om aan de norm te voldoen. Deze druk kan intern zijn, zoals perfectionisme en faalangst, of extern, zoals verwachtingen van ouders, leerkrachten of de maatschappij. In een tijd waarin sociale media succes en perfectie benadrukken, voelen jongeren zich steeds vaker beoordeeld op hun prestaties, cijfers en zichtbare resultaten. De constante vergelijking met anderen draagt bij aan een verhoogd gevoel van falen of tekortschieten." },
      { title: "Hoe is het te herkennen?", content: "Jongeren die onder prestatiedruk staan, vertonen vaak signalen zoals overmatige bezorgdheid over cijfers, uitstelgedrag, slapeloosheid en concentratieproblemen. Zij durven vaak geen hulp te vragen uit angst als zwak te worden gezien en zijn voortdurend bezig met het vermijden van fouten. Fysiek kunnen spanningsklachten optreden zoals hoofdpijn, maagpijn of vermoeidheid. Psychisch uit het zich in perfectionisme, zelfkritiek, emotionele uitputting of gevoelens van minderwaardigheid." },
      { title: "Welke aanpak is mogelijk?", content: "Een eerste stap in het aanpakken van prestatiedruk is het creëren van een realistisch zelfbeeld en het herdefiniëren van succes. Het is belangrijk om haalbare doelen te stellen en niet te streven naar perfectie. Ondersteuning vanuit de omgeving is cruciaal: ouders, leerkrachten en begeleiders kunnen helpen door erkenning te geven aan inspanning in plaats van enkel aan resultaat. Het aanleren van time-managementvaardigheden, het plannen van ontspanning en het bespreekbaar maken van de ervaren druk dragen bij aan de afname ervan. Verder kunnen ontspanningstechnieken zoals ademhalingsoefeningen, mindfulness of lichaamsbeweging helpen om spanningsklachten te verminderen." },
      { title: "Wanneer en waar hulp zoeken?", content: "Indien prestatiedruk leidt tot ernstige klachten zoals burn-outsymptomen, depressieve gevoelens of schooluitval, is het noodzakelijk professionele hulp in te schakelen. Het CLB, een psycholoog of een schoolbegeleider kunnen ondersteuning bieden via gesprekken, coaching of therapie gericht op stressmanagement, zelfbeeld en faalangst. Vroegtijdige interventie is belangrijk om chronische klachten en verdere uitval te voorkomen." },
      { title: "Wist je dat...?", content: "Uit Vlaams onderzoek blijkt dat prestatiedruk nauw samenhangt met het gebruik van sociale media, waarbij jongeren zichzelf voortdurend vergelijken met anderen. Ook blijkt dat jongeren vaak meer druk ervaren van zichzelf dan van hun ouders of leerkrachten. Een klimaat waarin fouten maken gezien wordt als leermoment, kan de schadelijke effecten van prestatiedruk aanzienlijk verminderen." },
    ],
  },
];

export default function Home() {
  return (
    <main className="scroll-pt-20 p-4 pt-24 max-w-3xl mx-auto text-[var(--foreground)] bg-[var(--background)]">
      <Navbar />
      {sections.map((section) => (
        <section key={section.id} id={section.id} className="mb-8">
          <h2 className="text-2xl font-bold text-black mb-2">{section.title}</h2>
          {section.subsections.map((sub, i) => (
            <CollapsibleSection key={i} title={sub.title} content={sub.content} />
          ))}
        </section>
      ))}
    </main>
  );
}
